matrix:
- name: open-atmos-krk
  hunspell:
    lang: en_GB
    encoding: utf-8
    dictionary:
      wordlists:
        - .wordlist.txt
  pipeline:
    - pyspelling.filters.html:
        comments: false
        ignores:
          - code
          - pre
    - pyspelling.filters.context:
        context_visible_first: true
        delimiters:
          - open: '\bLEAP Science and Technology Center\b'
            close: '\bLEAP Science and Technology Center\b'
          - open: '\bet al\.\b'
            close: '\bet al\.\b'
          - open: "\\bCeci n'est pas un superordinateur\\b"
            close: "\\bCeci n'est pas un superordinateur\\b"

  sources:
    - './_site/**/*.html' 

  default_encoding: utf-8
