matrix:
- name: open-atmos-krk
  hunspell:
    d: en_GB
  dictionary:
    wordlists:
      - .wordlist.txt
    encoding: utf-8
  pipeline:
    - pyspelling.filters.html:
        comments: false
        ignores:
          - code
          - pre
          - sup
          - cite
          - span.emoji
    - pyspelling.filters.context:
        context_visible_first: true
        delimiters:
          - open: '\bet al\.\b'
            close: '\bet al\.\b'
          - open: '\bopen-atmos-jupyter-utils\b'
            close: '\bopen-atmos-jupyter-utils\b'
          - open: '\bopen-atmos-krk\b'
            close: '\bopen-atmos-krk\b'
          - open: "\\bfis\\.agh\\.edu\\.pl\\b"
            close: "\\bfis\\.agh\\.edu\\.pl\\b"
          - open: "\\buj\\.edu\\.pl\\b"
            close: "\\buj\\.edu\\.pl\\b"
          - open: "\\bagh\\.edu\\.pl\\b"
            close: "\\bagh\\.edu\\.pl\\b"
          - open: "\\bzfs\\.agh\\.edu\\.pl\\b"
            close: "\\bzfs\\.agh\\.edu\\.pl\\b"
          - open: "\\bgithub\\.com\/open-atmos\\b"
            close: "\\bgithub\\.com\/open-atmos\\b"

  sources:
    - './_site/**/*.html' 

  default_encoding: utf-8
