matrix:
- name: spellcheck
  aspell:
    lang: en
    d: en_GB
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - './_site/**/*.html' 
  default_encoding: utf-8
