matrix:
- name: open-atmos-krk
  hunspell:
    d: en_GB
  dictionary:
    wordlists:
      - .wordlist.txt
    encoding: utf-8
  pipeline:
    - pyspelling.filters.html:
        comments: false
        ignores:
          - code
          - pre
    - pyspelling.filters.context:
        context_visible_first: true
        delimiters:
          - open: '\bLEAP Science and Technology Center\b'
            close: '\bLEAP Science and Technology Center\b'
          - open: '\bet al\.\b'
            close: '\bet al\.\b'
          - open: '\bopen-atmos-jupyter-utils\b'
            close: '\bopen-atmos-jupyter-utils\b'
          - open: '\bopen-atmos-krk\b'
            close: '\bopen-atmos-krk\b'
          - open: "\\bCeci n'est pas un superordinateur\\b"
            close: "\\bCeci n'est pas un superordinateur\\b"
          - open: "\\bDynamics and Self-Organization\\b"
            close: "\\bDynamics and Self-Organization\\b"

  sources:
    - './_site/**/*.html' 

  default_encoding: utf-8
