matrix:
- name: open-atmos-krk
  aspell:
    lang: en
    d: en_GB
  dictionary:
    wordlists:
      - .wordlist.txt
    encoding: utf-8
  pipeline:
    - pyspelling.filters.html:
        comments: false
        ignores:
          - code
          - pre
    - pyspelling.filters.context:
        context_visible_first: true
        contexts_hide:
          - ['(?i)LEAP Science and Technology Center', '']
  sources:
    - './_site/**/*.html' 

  default_encoding: utf-8
