matrix:
- name: open-atmos-krk
  hunspell:
    d: en_GB
  dictionary:
    wordlists:
      - .wordlist.txt
    encoding: utf-8
  pipeline:
    - pyspelling.filters.html:
        comments: false
        ignores:
          - code
          - pre
          - sup
          - cite
    - pyspelling.filters.context:
        context_visible_first: true
        delimiters:
          - open: '\bLEAP Science and Technology Center\b'
            close: '\bLEAP Science and Technology Center\b'
          - open: '\bet al\.\b'
            close: '\bet al\.\b'
          - open: '\bopen-atmos-jupyter-utils\b'
            close: '\bopen-atmos-jupyter-utils\b'
          - open: '\bopen-atmos-krk\b'
            close: '\bopen-atmos-krk\b'
          - open: "\\bCeci n'est pas un superordinateur\\b"
            close: "\\bCeci n'est pas un superordinateur\\b"
          - open: "\\bfis\\.agh\\.edu\\.pl\\b"
            close: "\\bfis\\.agh\\.edu\\.pl\\b"
          - open: "\\buj\\.edu\\.pl\\b"
            close: "\\buj\\.edu\\.pl\\b"
          - open: "\\bagh\\.edu\\.pl\\b"
            close: "\\bagh\\.edu\\.pl\\b"
          - open: "\\bzfs\\.agh\\.edu\\.pl\\b"
            close: "\\bzfs\\.agh\\.edu\\.pl\\b"
          - open: "\\bgithub\\.com\/open-atmos\\b"
            close: "\\bgithub\\.com\/open-atmos\\b"
          - open: "\\bDifferentialEquations\\.jl\\b"
            close: "\\bDifferentialEquations\\.jl\\b"
          - open: "\\bDroplets\\.jl\\b"
            close: "\\bDroplets\\.jl\\b"
          - open: "\\bpy-pde\\b"
            close: "\\bpy-pde\\b"
          - open: "\\bes_jobs_net\\b"
            close: "\\bes_jobs_net\\b"
          - open: "\\blibmpdata++\\b"
            close: "\\blibmpdata++\\b"
          - open: "\\bGeosci\\. Model Dev\\.\\b"
            close: "\\bGeosci\\. Model Dev\\.\\b"
          - open: "\\bInt\\. J\\. Numer\\. Methods Fluids\\b"
            close: "\\bInt\\. J\\. Numer\\. Methods Fluids\\b"
          - open: "\\bComm\\. Earth\\. Environ\\.\\b"
            close: "\\bComm\\. Earth\\. Environ\\.\\b"
          - open: '\biodine vapor\b'
            close: '\biodine vapor\b'
          - open: '\bby dual-polarization radar\b'
            close: '\bby dual-polarization radar\b'
          - open: 'Mini-workshop on particle-based cloud modeling 2025'
            close: 'Mini-workshop on particle-based cloud modeling 2025'
          - open: '\bIDL/PV-WAVE\b'
            close: '\bIDL/PV-WAVE\b'
          - open: '\bLa londe les Maures\b'
            close: '\bLa londe les Maures\b'
          - open: 'On Probabilistic Particle-Based Modeling of Immersion Freezing'
            close: 'On Probabilistic Particle-Based Modeling of Immersion Freezing'
          - open: 'Probabilistic Particle-Based Methods in Aerosol-Cloud Microphysics Modeling'
            close: 'Probabilistic Particle-Based Methods in Aerosol-Cloud Microphysics Modeling'
          - open: 'SCALES 2023 - Multiscale Modeling of Complex Systems'
            close: 'SCALES 2023 - Multiscale Modeling of Complex Systems'
          - open: 'SCALES Multiscale Modeling of Complex Systems'
            close: 'SCALES Multiscale Modeling of Complex Systems'
          - open: 'Continuous Integration with research notebooks: on maintaining reproducibility in atmospheric modeling'
            close: 'Continuous Integration with research notebooks: on maintaining reproducibility in atmospheric modeling'

  sources:
    - './_site/**/*.html' 

  default_encoding: utf-8
